/* =========================================================================
   Funding dataset — every funding source referenced at / adjacent to
   Fed Supernova (Capital Factory's defense-innovation conference).
   Figures verified against official agency pages as of the date below.
   Re-verify on the linked source before relying on any number.
   ========================================================================= */

const LAST_VERIFIED = "2026-06";

/* Facet vocabularies (order = display order) */
const FACETS = {
  dept: ["DoD", "DOE", "Civilian", "Cross-agency"],
  mechanism: [
    "SBIR / STTR", "R&D Contract / BAA", "Other Transaction (Prototype)",
    "Matching Funds", "Prize / Challenge", "Loan / Loan Guarantee",
    "Production Transition", "Accelerator"
  ],
  capital: ["Non-dilutive", "Debt (non-dilutive)"],
  award: ["< $100K", "$100K–$500K", "$500K–$2M", "$2M–$15M", "$15M+"],
  tech: [
    "Aerospace", "Space", "Autonomy / UAV", "Hypersonics", "Directed Energy",
    "Microelectronics", "RF / Sensors", "Energy / Power", "Propulsion",
    "Advanced Materials", "Cyber", "AI / ML", "Ballistics / Weapons", "Quantum"
  ]
};

const PROGRAMS = [
  {
    id: "dod-sbir",
    name: "DoD SBIR / STTR",
    funder: "DoD (all services)",
    dept: "DoD",
    mechanism: "SBIR / STTR",
    capital: "Non-dilutive",
    award: "$2M–$15M",
    typical: "Phase I ≤ $323,090 · Phase II ≤ $2,153,927",
    eligibility: "US small business, <500 employees, 51%+ US-owned.",
    tech: ["Aerospace", "RF / Sensors", "AI / ML", "Autonomy / UAV", "Advanced Materials"],
    desc: "The foundational non-dilutive R&D program across every military service. Phased funding from feasibility to prototype.",
    detail: "America's Seed Fund for defense. Phase I proves feasibility; Phase II builds and matures a prototype; Phase III transitions to production (no SBIR dollar cap). FY2026 SBA caps: Phase I up to $323,090 and Phase II up to $2,153,927 without an SBA waiver.",
    source: "https://www.sbir.gov"
  },
  {
    id: "afwerx",
    name: "AFWERX SBIR / STTR (Open Topic)",
    funder: "AFWERX (Dept. of the Air Force)",
    dept: "DoD",
    mechanism: "SBIR / STTR",
    capital: "Non-dilutive",
    award: "$500K–$2M",
    typical: "Ph I ≤ $75K (SBIR) / $110K (STTR) · Ph II ≤ $1.25M / $1.8M",
    eligibility: "US small business with an Air Force customer / dual-use tech.",
    tech: ["Aerospace", "Autonomy / UAV", "AI / ML", "RF / Sensors", "Directed Energy"],
    desc: "The Air Force's fast, company-led 'Open Topic' path — you pitch your own dual-use technology rather than answering a narrow topic.",
    detail: "AFWERX runs Open Topic SBIR/STTR cycles where founders propose their own solution. Phase I is a ~3-month feasibility study (up to $75K SBIR / $110K STTR); Phase II (up to $1.25M SBIR / $1.8M STTR) runs ~21–24 months. AFWERX announces STRATFI/TACFI selections at Fed Supernova.",
    source: "https://www.afwerx.com"
  },
  {
    id: "spacewerx",
    name: "SpaceWERX SBIR / STTR",
    funder: "SpaceWERX (US Space Force)",
    dept: "DoD",
    mechanism: "SBIR / STTR",
    capital: "Non-dilutive",
    award: "$500K–$2M",
    typical: "Same caps as AFWERX Open Topic",
    eligibility: "US small business with space / on-orbit dual-use technology.",
    tech: ["Space", "RF / Sensors", "Propulsion", "AI / ML"],
    desc: "The Space Force innovation arm — SBIR/STTR for on-orbit, launch, comms, and space-domain-awareness technology.",
    detail: "SpaceWERX mirrors the AFWERX Open Topic model for space technologies: on-orbit servicing, propulsion, space comms, SDA sensors. Also the gateway to STRATFI/TACFI matching for space startups, with selections announced at Fed Supernova.",
    source: "https://www.spacewerx.us"
  },
  {
    id: "stratfi",
    name: "STRATFI (Strategic Funding Increase)",
    funder: "AFWERX / SpaceWERX",
    dept: "DoD",
    mechanism: "Matching Funds",
    capital: "Non-dilutive",
    award: "$2M–$15M",
    typical: "$3M–$15M (government + private matching)",
    eligibility: "Active or recent SBIR Phase II awardee with a DAF/USSF need + private match.",
    tech: ["Aerospace", "Space", "Autonomy / UAV", "AI / ML", "RF / Sensors"],
    desc: "The 'valley of death' bridge — blends SBIR, government, and matching private dollars to scale a Phase II into a program of record.",
    detail: "STRATFI combines SBIR funds, additional government money, and matched private capital into a single $3M–$15M package to bridge Phase II to Phase III. Cumulatively, AFWERX/SpaceWERX have made 184 STRATFI/TACFI awards to 158 companies ($583M SBIR + $702M government + $619M private match).",
    source: "https://www.afwerx.com/divisions/ventures/"
  },
  {
    id: "tacfi",
    name: "TACFI (Tactical Funding Increase)",
    funder: "AFWERX / SpaceWERX",
    dept: "DoD",
    mechanism: "Matching Funds",
    capital: "Non-dilutive",
    award: "$500K–$2M",
    typical: "$375K–$2M (government + private matching)",
    eligibility: "Active or recent SBIR Phase II awardee with a DAF/USSF need + private match.",
    tech: ["Aerospace", "Space", "AI / ML", "RF / Sensors"],
    desc: "A smaller, faster matching-funds bridge than STRATFI for maturing a Phase II effort toward transition.",
    detail: "TACFI provides $375K–$2M of blended government + matched private funding to keep momentum between Phase II and a production contract. Selections are announced at events including Fed Supernova.",
    source: "https://www.afwerx.com/divisions/ventures/"
  },
  {
    id: "diu-cso",
    name: "DIU Commercial Solutions Opening (CSO)",
    funder: "Defense Innovation Unit (DIU)",
    dept: "DoD",
    mechanism: "Other Transaction (Prototype)",
    capital: "Non-dilutive",
    award: "$500K–$2M",
    typical: "Prototype OTs ~$500K–$5M · award in 60–90 days",
    eligibility: "Any entity; commercial / nontraditional vendors favored.",
    tech: ["AI / ML", "Autonomy / UAV", "Cyber", "Space", "Energy / Power"],
    desc: "The fastest DoD on-ramp for commercial tech — prototype Other Transaction agreements awarded in as little as 60–90 days.",
    detail: "DIU uses the CSO / Other Transaction authority to prototype commercial technology against real warfighter problems. 450+ prototype OTs and $1.7B since 2016, with a ~51% transition rate to production. Successful prototypes can convert to sole-source production under 10 U.S.C. § 4022.",
    source: "https://www.diu.mil"
  },
  {
    id: "nsic",
    name: "NSIC (National Security Innovation Capital)",
    funder: "NSIC (within DIU)",
    dept: "DoD",
    mechanism: "Other Transaction (Prototype)",
    capital: "Non-dilutive",
    award: "$500K–$2M",
    typical: "$500K–$3M fixed-price OT · 12–18 month performance",
    eligibility: "US dual-use hardware startup at TRL 3+.",
    tech: ["Autonomy / UAV", "RF / Sensors", "Space", "Energy / Power", "Microelectronics"],
    desc: "Non-dilutive hardware capital for dual-use startups — funds hardware development so founders don't rely on adversarial capital.",
    detail: "NSIC funds the development of dual-use hardware (autonomy, communications, sensors, space, power) with $500K–$3M fixed-price Other Transaction agreements over 12–18 months. Reviews are periodically paused when funds are fully committed — verify intake status before relying on it.",
    source: "https://www.diu.mil/nsic"
  },
  {
    id: "darpa",
    name: "DARPA Broad Agency Announcement (BAA)",
    funder: "DARPA",
    dept: "DoD",
    mechanism: "R&D Contract / BAA",
    capital: "Non-dilutive",
    award: "$2M–$15M",
    typical: "~$500K–$5M+ · contracts, grants, cooperative agreements, OTs",
    eligibility: "Any qualified performer (company, university, individual).",
    tech: ["AI / ML", "Microelectronics", "Hypersonics", "Space", "Directed Energy", "Quantum"],
    desc: "High-risk, high-reward breakthrough research across six technical offices with a ~$4.9B FY2026 budget.",
    detail: "DARPA's primary instrument is the BAA. Awards range from ~$500K to $5M+ and can be contracts, grants, cooperative agreements, or Other Transactions. Ideal for founders with genuinely novel, physics-hard technology that needs validation.",
    source: "https://www.darpa.mil/work-with-us/opportunities"
  },
  {
    id: "army-xtech",
    name: "Army xTech (Search / Pacific / etc.)",
    funder: "US Army (ASA ALT)",
    dept: "DoD",
    mechanism: "Prize / Challenge",
    capital: "Non-dilutive",
    award: "$500K–$2M",
    typical: "Prizes up to ~$900K + a path to SBIR ($250K–$2M)",
    eligibility: "US small business (some tracks open to large firms).",
    tech: ["Ballistics / Weapons", "Autonomy / UAV", "Energy / Power", "Advanced Materials", "AI / ML"],
    desc: "Army prize competitions with cash awards and a direct on-ramp into SBIR — no lengthy proposal to start.",
    detail: "xTech runs pitch-based prize competitions (xTechSearch, xTechPacific, and themed challenges). Example: xTechSearch 9 offered up to $900K in prizes plus a path to a $250K SBIR Phase I; xTechPacific offered up to $345K plus Direct-to-Phase-II up to $2M.",
    source: "https://www.xtech.army.mil"
  },
  {
    id: "onr-navy",
    name: "ONR / Navy SBIR + Open BAA",
    funder: "Office of Naval Research / DoN",
    dept: "DoD",
    mechanism: "R&D Contract / BAA",
    capital: "Non-dilutive",
    award: "$500K–$2M",
    typical: "SBIR caps · plus large 'Open' BAA pools (e.g., $50M)",
    eligibility: "US small business; naval S&T relevance.",
    tech: ["RF / Sensors", "Autonomy / UAV", "Energy / Power", "Advanced Materials", "AI / ML"],
    desc: "Naval science & technology funding across 30+ areas, plus NavalX / TechSolutions rapid non-dilutive support.",
    detail: "ONR funds SBIR/STTR and 'Open' BAAs across 30+ naval S&T areas. NavalX and TechSolutions provide rapid, non-dilutive support and a path to sole-source contracts within five years for solutions to naval problem sets.",
    source: "https://www.onr.navy.mil"
  },
  {
    id: "osc",
    name: "Office of Strategic Capital (OSC)",
    funder: "Office of Strategic Capital",
    dept: "DoD",
    mechanism: "Loan / Loan Guarantee",
    capital: "Debt (non-dilutive)",
    award: "$15M+",
    typical: "$10M–$150M loans / guarantees · tenors up to 50 years",
    eligibility: "US company, 3+ yr history, in a covered technology category.",
    tech: ["Microelectronics", "Advanced Materials", "Quantum", "Energy / Power", "Space"],
    desc: "Long-tenor federal loans and loan guarantees for capital-intensive 'covered technology' — debt, not equity.",
    detail: "OSC provides loans and loan guarantees ($10M–$150M, up to $984M authority through FY26) at Treasury-based rates with tenors up to 50 years, across 31 covered technology categories, with an 80% non-federal capital requirement. Highly leveraged: a few million in outlays can back billions in guarantees.",
    source: "https://www.cto.mil/osc/"
  },
  {
    id: "apfit",
    name: "APFIT (Accelerate Procurement & Fielding)",
    funder: "OUSD(R&E)",
    dept: "DoD",
    mechanism: "Production Transition",
    capital: "Non-dilutive",
    award: "$15M+",
    typical: "$10M–$50M to move tech from development into production",
    eligibility: "Small business / nontraditional with a late-stage, transition-ready product.",
    tech: ["Autonomy / UAV", "Microelectronics", "RF / Sensors", "Advanced Materials"],
    desc: "Bridges the final gap to fielding — funds the jump from a matured prototype into actual production.",
    detail: "Made permanent in the FY2025 NDAA, APFIT invests $10M–$50M to accelerate late-stage transition. Since inception it has invested over $925M across 46 projects in 20 states, attracting over $2B in follow-on procurement.",
    source: "https://www.cto.mil"
  },
  {
    id: "me-commons",
    name: "Microelectronics Commons",
    funder: "DoD (CHIPS via NSWC Crane / NSTXL)",
    dept: "Cross-agency",
    mechanism: "Other Transaction (Prototype)",
    capital: "Non-dilutive",
    award: "$2M–$15M",
    typical: "$2B program · 8 regional hubs · first round $269M / 33 projects",
    eligibility: "Members of a regional hub (companies, universities, startups).",
    tech: ["Microelectronics", "AI / ML", "Quantum", "RF / Sensors", "Directed Energy"],
    desc: "CHIPS-funded network of 8 regional hubs turning lab-scale microelectronics into domestic prototypes.",
    detail: "A $2B CHIPS-funded effort managed via NSWC Crane and NSTXL across 8 regional hubs. Focus areas: AI hardware, electromagnetic/electronic warfare, quantum, secure edge/IoT, 5G/6G, and commercial leap-ahead. First round funded 33 projects worth $269M.",
    source: "https://www.microelectronicscommons.org"
  },
  {
    id: "nsin",
    name: "NSIN (Propel / Emerge / Vector)",
    funder: "National Security Innovation Network",
    dept: "DoD",
    mechanism: "Accelerator",
    capital: "Non-dilutive",
    award: "< $100K",
    typical: "Accelerator support + up to ~$50K commercialization funding",
    eligibility: "University / venture startups, TRL 4+.",
    tech: ["AI / ML", "Autonomy / UAV", "Cyber", "RF / Sensors"],
    desc: "DoD accelerators connecting university and venture-stage deep-tech teams to defense customers.",
    detail: "NSIN runs cohort accelerators (Propel, Emerge, Vector) that connect early teams to DoD problem owners. Funding is often non-monetary (mentorship, customer access) with some commercialization grants — a low-friction first touchpoint with the defense market.",
    source: "https://www.nsin.mil"
  },
  {
    id: "nasa-sbir",
    name: "NASA SBIR / STTR + iTech",
    funder: "NASA",
    dept: "Civilian",
    mechanism: "SBIR / STTR",
    capital: "Non-dilutive",
    award: "$500K–$2M",
    typical: "Phase I ≤ $150K · SBIR Ignite Phase II ≤ $850K",
    eligibility: "US small business; space / aeronautics relevance.",
    tech: ["Space", "Propulsion", "Advanced Materials", "Aerospace"],
    desc: "Civilian space-technology seed funding — propulsion, in-space manufacturing, and aeronautics.",
    detail: "NASA's SBIR/STTR funds feasibility (Phase I up to $150K) and development (SBIR Ignite Phase II up to $850K). iTech surfaces breakthrough concepts. A strong complement for dual-use space startups also pursuing SpaceWERX.",
    source: "https://sbir.nasa.gov"
  },
  {
    id: "nsf-sbir",
    name: "NSF SBIR / STTR (America's Seed Fund)",
    funder: "National Science Foundation",
    dept: "Civilian",
    mechanism: "SBIR / STTR",
    capital: "Non-dilutive",
    award: "$500K–$2M",
    typical: "Phase I ≤ $305K · Phase II ≤ $1.25M (+ IIB match ≤ $500K)",
    eligibility: "US small business with deep-tech, no equity taken.",
    tech: ["AI / ML", "Advanced Materials", "Microelectronics", "Energy / Power", "Quantum"],
    desc: "Broad deep-tech seed funding (~$200M/yr to ~400 startups) with no equity and no defense-specific requirement.",
    detail: "NSF's America's Seed Fund backs nearly all deep-tech: Phase I up to $305K, Phase II up to $1.25M, plus Phase IIB matching up to $500K. Fully non-dilutive — a great parallel track for defense-adjacent startups with commercial applications.",
    source: "https://seedfund.nsf.gov"
  },
  {
    id: "doe-sbir",
    name: "DOE SBIR / STTR",
    funder: "Dept. of Energy",
    dept: "DOE",
    mechanism: "SBIR / STTR",
    capital: "Non-dilutive",
    award: "$100K–$500K",
    typical: "Phase I ≤ $200K (varies by solicitation)",
    eligibility: "US small business; energy / grid / materials relevance.",
    tech: ["Energy / Power", "Advanced Materials", "Microelectronics"],
    desc: "Energy-focused seed funding administered through the DOE Office of Science and program offices.",
    detail: "DOE SBIR/STTR (Phase I up to ~$200K, varying by solicitation) funds energy, grid, and advanced-materials technologies — relevant for power electronics, batteries, and thermal-management startups that also serve defense.",
    source: "https://science.osti.gov/sbir"
  },
  {
    id: "arpa-e",
    name: "ARPA-E (OPEN / SCALEUP)",
    funder: "ARPA-E (DOE)",
    dept: "DOE",
    mechanism: "R&D Contract / BAA",
    capital: "Non-dilutive",
    award: "$2M–$15M",
    typical: "$250K–$10M cooperative agreements",
    eligibility: "Universities, labs, industry, and individuals.",
    tech: ["Energy / Power", "Advanced Materials", "Propulsion"],
    desc: "Transformational energy R&D — high-impact awards for breakthrough power, storage, and generation technology.",
    detail: "ARPA-E's OPEN program funds transformational energy concepts ($250K–$10M; Vision OPEN 2024 awarded $147M across 49 projects). SCALEUP helps prior awardees scale. Strong fit for electric-propulsion, power-electronics, and energy-storage founders.",
    source: "https://arpa-e.energy.gov"
  }
];
